# This code is for Elastic file provisioning 

# Creating the PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # This should be empty in static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0bce55c2a5841e18c # give our created volume in EFS
---
# Creating the PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
# Creating the POD, Inside POD we are creating a container and creating the volume and 
# that volume is mounted for EFS Drive
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static
---
# Creating Load balancer service we are accessing it from extrenal site in internet
apiVersion: v1
kind: Service
metadata:
  name: efs-static
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

