# This code is for environmental variables and this is the main code we dont want to 
# change any specifications in this code
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "KUBERENETS"
    - name: TRAINER
      value: "JANARDHAN"


# we can check the env variables while running PODS, you can see the env variables
# kubectl exec -it resource name which we create --bash