# This code is for environmental variables
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "KUBERENETS"
    - name: TRAINER
      value: "SIVAKUMAR REDDY M"


# we can check the env variables while running PODS, you can see the env variables