# This code is for creating a secret resource includes passwords,api etc..

apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque # we are create it ourselves
data:
  username: "YWRtaW4="
  password: "YWRtaW4zMjE="

  